#!/bin/bash
[[ "$-" =~ i ]] || return

# LS_COLORS_GREEN="38;5;40"
LS_COLORS_LIGHTBLUE="38;5;81"
LS_COLORS_WHITE="38;5;253"
LS_COLORS_ORANGE="38;5;184"
LS_COLORS_DARKGREY="38;5;244"
LS_COLORS_RED="38;5;9"


# By def
LS_COLORS_IGNORE="38;5;60"
LS_COLORS_ARCHIVE="38;5;40"

LS_COLORS=""

N=0

if [[ "${N}" == 0 ]]
then
LS_COLORS="${LS_COLORS}:bd=38;5;68"
LS_COLORS="${LS_COLORS}:ca=38;5;17"
LS_COLORS="${LS_COLORS}:cd=38;5;113;1"
LS_COLORS="${LS_COLORS}:di=38;5;30"
LS_COLORS="${LS_COLORS}:do=38;5;127"
LS_COLORS="${LS_COLORS}:ex=38;5;208;1"
LS_COLORS="${LS_COLORS}:pi=38;5;126"
LS_COLORS="${LS_COLORS}:fi=0"
LS_COLORS="${LS_COLORS}:ln=target"
LS_COLORS="${LS_COLORS}:mh=38;5;222;1"
LS_COLORS="${LS_COLORS}:no=0"
LS_COLORS="${LS_COLORS}:or=48;5;196;38;5;232;1"
LS_COLORS="${LS_COLORS}:ow=38;5;220;1"
LS_COLORS="${LS_COLORS}:sg=48;5;3;38;5;0"
LS_COLORS="${LS_COLORS}:su=38;5;220;1;3;100;1"
LS_COLORS="${LS_COLORS}:so=38;5;197"
LS_COLORS="${LS_COLORS}:st=38;5;86;48;5;234"
LS_COLORS="${LS_COLORS}:tw=48;5;235;38;5;139;3"

else
LS_COLORS="${LS_COLORS}:bd=48;5;232;38;5;11"
LS_COLORS="${LS_COLORS}:ca=48;5;196;38;5;226"
LS_COLORS="${LS_COLORS}:cd=48;5;232;38;5;3"
LS_COLORS="${LS_COLORS}:di=38;5;27"
LS_COLORS="${LS_COLORS}:do=38;5;5"
LS_COLORS="${LS_COLORS}:ex=38;5;34"
LS_COLORS="${LS_COLORS}:ln=38;5;51"
LS_COLORS="${LS_COLORS}:mh=44;38;5;15"
LS_COLORS="${LS_COLORS}:mi=05;48;5;232;38;5;15"
LS_COLORS="${LS_COLORS}:or=48;5;232;38;5;9"
LS_COLORS="${LS_COLORS}:ow=48;5;10;38;5;21"
LS_COLORS="${LS_COLORS}:pi=40;38;5;11"
LS_COLORS="${LS_COLORS}:rs=0"
LS_COLORS="${LS_COLORS}:sg=48;5;11;38;5;16"
LS_COLORS="${LS_COLORS}:so=38;5;13"
LS_COLORS="${LS_COLORS}:st=48;5;21;38;5;15"
LS_COLORS="${LS_COLORS}:su=48;5;196;38;5;15"
LS_COLORS="${LS_COLORS}:tw=48;5;10;38;5;16"

fi

# Archives
# --------------------------------------
LS_COLORS="${LS_COLORS}:*.7z=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.WARC=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.a=${LS_COLORS_GREEN}"
# LS_COLORS="${LS_COLORS}:*.arj=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.bz2=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.cpio=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.gz=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.lrz=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.lz=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.lzma=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.lzo=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.rar=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.s7z=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.sz=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.tar=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.tbz=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.tgz=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.warc=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.xz=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.z=${LS_COLORS_ARCHIVE}"
LS_COLORS="${LS_COLORS}:*.zip=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.zipx=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.zoo=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.zpaq=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.zst=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.zstd=${LS_COLORS_ARCHIVE}"
# LS_COLORS="${LS_COLORS}:*.zz=${LS_COLORS_ARCHIVE}"
#
# LS_COLORS="${LS_COLORS}:*@.service=38;5;45"

# Packages
# --------------------------------------
LS_COLORS="${LS_COLORS}:*.deb=${LS_COLORS_RED}"
LS_COLORS="${LS_COLORS}:*.rpm=${LS_COLORS_RED}"

# Code additional
# --------------------------------------
LS_COLORS="${LS_COLORS}:*AUTHORS=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*CHANGES=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*CONTRIBUTORS=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*COPYING=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*COPYRIGHT=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*CodeResources=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*HISTORY=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*INSTALL=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*LICENSE=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*MANIFEST=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*NOTICE=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*PATENTS=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*VERSION=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*PkgInfo=${LS_COLORS_IGNORE}"


# Make / Build files
# --------------------------------------
LS_COLORS="${LS_COLORS}:*Dockerfile=38;5;155"
LS_COLORS="${LS_COLORS}:*Makefile=38;5;155"

# Documentation
# --------------------------------------
LS_COLORS="${LS_COLORS}:*core=38;5;241"
LS_COLORS="${LS_COLORS}:*.rst=${LS_COLORS_ORANGE}"
LS_COLORS="${LS_COLORS}:*.md=${LS_COLORS_ORANGE}"


# SSH
# --------------------------------------
LS_COLORS="${LS_COLORS}:*id_dsa=38;5;192;3"
LS_COLORS="${LS_COLORS}:*id_ecdsa=38;5;192;3"
LS_COLORS="${LS_COLORS}:*id_ed25519=38;5;192;3"
LS_COLORS="${LS_COLORS}:*id_rsa=38;5;192;3"
#
# LS_COLORS="${LS_COLORS}:*.C=${LS_COLORS_LIGHTBLUE}"
# LS_COLORS="${LS_COLORS}:*.H=38;5;110"

LS_COLORS="${LS_COLORS}:*.awk=38;5;172"
LS_COLORS="${LS_COLORS}:*.bash=38;5;172"
LS_COLORS="${LS_COLORS}:*.c=${LS_COLORS_LIGHTBLUE}"
LS_COLORS="${LS_COLORS}:*.c++=${LS_COLORS_LIGHTBLUE}"
LS_COLORS="${LS_COLORS}:*.cpp=${LS_COLORS_LIGHTBLUE}"
LS_COLORS="${LS_COLORS}:*.db=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*.doc=38;5;111"
LS_COLORS="${LS_COLORS}:*.dockerignore=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*.docm=38;5;111;4"
LS_COLORS="${LS_COLORS}:*.docx=38;5;111"
LS_COLORS="${LS_COLORS}:*.git=38;5;197"
LS_COLORS="${LS_COLORS}:*.gitattributes=38;5;240"
LS_COLORS="${LS_COLORS}:*.gitignore=38;5;240"
LS_COLORS="${LS_COLORS}:*.gitmodules=38;5;240"
LS_COLORS="${LS_COLORS}:*.go=${LS_COLORS_LIGHTBLUE}"
LS_COLORS="${LS_COLORS}:*.gpg=38;5;192;3"
LS_COLORS="${LS_COLORS}:*.h=38;5;110"
LS_COLORS="${LS_COLORS}:*.h++=38;5;110"
LS_COLORS="${LS_COLORS}:*.htm=38;5;125;1"
LS_COLORS="${LS_COLORS}:*.html=38;5;125;1"
LS_COLORS="${LS_COLORS}:*.iso=38;5;124"
LS_COLORS="${LS_COLORS}:*.localstorage=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*.log=38;5;190"
LS_COLORS="${LS_COLORS}:*.lua=${LS_COLORS_LIGHTBLUE}"
LS_COLORS="${LS_COLORS}:*.markdown=${LS_COLORS_ORANGE}"
LS_COLORS="${LS_COLORS}:*.md5=38;5;116"
LS_COLORS="${LS_COLORS}:*.nc=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*.pdf=38;5;141"
LS_COLORS="${LS_COLORS}:*.pem=38;5;192;3"
LS_COLORS="${LS_COLORS}:*.pgp=38;5;192;3"
LS_COLORS="${LS_COLORS}:*.php=${LS_COLORS_LIGHTBLUE}"
LS_COLORS="${LS_COLORS}:*.pl=38;5;208"
LS_COLORS="${LS_COLORS}:*.pod=${LS_COLORS_ORANGE}"
LS_COLORS="${LS_COLORS}:*.py=${LS_COLORS_LIGHTBLUE}"
LS_COLORS="${LS_COLORS}:*.pyc=${LS_COLORS_DARKGREY}"
LS_COLORS="${LS_COLORS}:*.pyo=${LS_COLORS_DARKGREY}"
LS_COLORS="${LS_COLORS}:*.sed=38;5;172"
LS_COLORS="${LS_COLORS}:*.sh=38;5;172"
LS_COLORS="${LS_COLORS}:*.sqlite=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*.swo=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*.swp=${LS_COLORS_IGNORE}"
LS_COLORS="${LS_COLORS}:*.tex=${LS_COLORS_ORANGE}"
LS_COLORS="${LS_COLORS}:*.toml=38;5;178"
LS_COLORS="${LS_COLORS}:*.ts=38;5;115"
LS_COLORS="${LS_COLORS}:*.tsv=38;5;78"
LS_COLORS="${LS_COLORS}:*.txt=${LS_COLORS_WHITE}"
LS_COLORS="${LS_COLORS}:*.vim=38;5;172"
LS_COLORS="${LS_COLORS}:*.xls=38;5;112"
LS_COLORS="${LS_COLORS}:*.xlsx=38;5;112"
LS_COLORS="${LS_COLORS}:*.xlsxm=38;5;112;4"
LS_COLORS="${LS_COLORS}:*.xml=38;5;178"
LS_COLORS="${LS_COLORS}:*.yaml=38;5;178"
LS_COLORS="${LS_COLORS}:*.yml=38;5;178"
LS_COLORS="${LS_COLORS}:*authorized_keys=1"
LS_COLORS="${LS_COLORS}:*cfg=1"
LS_COLORS="${LS_COLORS}:*conf=1"
LS_COLORS="${LS_COLORS}:*config=1"
LS_COLORS="${LS_COLORS}:*known_hosts=1"
export LS_COLORS

# unset LS_COLORS_GREEN
unset LS_COLORS_LIGHTBLUE
unset LS_COLORS_WHITE
unset LS_COLORS_ORANGE
unset LS_COLORS_DARKGREY
unset LS_COLORS_RED
unset LS_COLORS_IGNORE
unset LS_COLORS_ARCHIVE
