#!/bin/bash
#===============================================================================
#
#         FILE:  tmux_opt_source
#
#        USAGE:  tmux_opt_source
#
#  DESCRIPTION:  source optional configurations if applicable
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  John van Zantvoort (jvzantvoort), john@vanzantvoort.org
#      COMPANY:  JDC
#      CREATED:  07-Apr-2019
#
# Copyright (C) 2019 John van Zantvoort
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#===============================================================================

CONST_SCRIPTPATH="$(readlink -f "$0")"
CONST_SCRIPTNAME="$(basename "$CONST_SCRIPTPATH" .sh)"
CONST_SCRIPTDIR="$(dirname "$CONST_SCRIPTPATH")"

readonly CONST_SCRIPTPATH
readonly CONST_SCRIPTNAME
readonly CONST_SCRIPTDIR

function source_if_exists()
{
  local CONFIGFILE=$1; shift
  if [ -f "${CONST_SCRIPTDIR}/${CONFIGFILE}" ]
  then
    tmux source-file "${CONST_SCRIPTDIR}/${CONFIGFILE}"
    return 0
  fi

  return 1
}

#------------------------------------------------------------------------------#
#                                    Main                                      #
#------------------------------------------------------------------------------#

THEME=$1; shift
SOURCED="no"

[[ -z "${THEME}" ]] && THEME="default.tmuxtheme"
if [ "${THEME}" = "--help" ]
then
  echo "${CONST_SCRIPTPATH} <theme name>"
  echo ""
  echo "example use:"
  echo ""
  echo "git clone https://github.com/jimeh/tmux-themepack.git"
  echo ""
  echo "The in the configuration:"
  echo ""
  echo "run-shell \"bash ~/.bash/tmux.d/${CONST_SCRIPTNAME} tmux-themepack/powerline/block/gray.tmuxtheme\""
  echo ""
  exit 0
fi

source_if_exists "${THEME}" && SOURCED="yes"

[[ "${SOURCED}" = "yes" ]] && exit 0

for theme in "$@"
do
  source_if_exists "${theme}" && exit 0
done

source_if_exists "default.tmuxtheme"

#------------------------------------------------------------------------------#
#                                  The End                                     #
#------------------------------------------------------------------------------#
